// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    riverpodStorage,
    libraries,
    series,
    seriesMetadata,
    seriesCovers,
    people,
    genres,
    tags,
    seriesPeopleRoles,
    seriesGenres,
    seriesTags,
    volumes,
    volumeCovers,
    chapters,
    chapterCovers,
    readingProgress,
    bookChapters,
    wantToRead,
    downloadedPages,
    serverSettings,
  ];
  late final Shape0 riverpodStorage = Shape0(
    source: i0.VersionedTable(
      entityName: 'riverpod_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 libraries = Shape1(
    source: i0.VersionedTable(
      entityName: 'libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 series = Shape2(
    source: i0.VersionedTable(
      entityName: 'series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, library_id)'],
      columns: [
        _column_4,
        _column_7,
        _column_5,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 seriesMetadata = Shape3(
    source: i0.VersionedTable(
      entityName: 'series_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 seriesCovers = Shape4(
    source: i0.VersionedTable(
      entityName: 'series_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 people = Shape5(
    source: i0.VersionedTable(
      entityName: 'people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 genres = Shape6(
    source: i0.VersionedTable(
      entityName: 'genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tags = Shape6(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 seriesPeopleRoles = Shape7(
    source: i0.VersionedTable(
      entityName: 'series_people_roles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, person_id)'],
      columns: [_column_33, _column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 seriesGenres = Shape8(
    source: i0.VersionedTable(
      entityName: 'series_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, genre_id)'],
      columns: [_column_33, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 seriesTags = Shape9(
    source: i0.VersionedTable(
      entityName: 'series_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, tag_id)'],
      columns: [_column_33, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 volumes = Shape10(
    source: i0.VersionedTable(
      entityName: 'volumes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_38,
        _column_39,
        _column_40,
        _column_13,
        _column_41,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 volumeCovers = Shape11(
    source: i0.VersionedTable(
      entityName: 'volume_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(volume_id)'],
      columns: [_column_43, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 chapters = Shape12(
    source: i0.VersionedTable(
      entityName: 'chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, volume_id, series_id)'],
      columns: [
        _column_4,
        _column_44,
        _column_25,
        _column_45,
        _column_46,
        _column_47,
        _column_26,
        _column_48,
        _column_11,
        _column_49,
        _column_38,
        _column_39,
        _column_50,
        _column_41,
        _column_51,
        _column_14,
        _column_15,
        _column_16,
        _column_52,
        _column_17,
        _column_18,
        _column_53,
        _column_54,
        _column_55,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 chapterCovers = Shape13(
    source: i0.VersionedTable(
      entityName: 'chapter_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [_column_56, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 readingProgress = Shape14(
    source: i0.VersionedTable(
      entityName: 'reading_progress',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [
        _column_56,
        _column_44,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 bookChapters = Shape15(
    source: i0.VersionedTable(
      entityName: 'book_chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page, title)'],
      columns: [_column_56, _column_65, _column_66, _column_67],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 wantToRead = Shape16(
    source: i0.VersionedTable(
      entityName: 'want_to_read',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_68, _column_64],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 downloadedPages = Shape17(
    source: i0.VersionedTable(
      entityName: 'downloaded_pages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page)'],
      columns: [_column_56, _column_66, _column_69, _column_62, _column_70],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 serverSettings = Shape18(
    source: i0.VersionedTable(
      entityName: 'server_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_71, _column_72, _column_73],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get data =>
      columnsByName['data']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get expireAt =>
      columnsByName['expire_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get destroyKey =>
      columnsByName['destroy_key']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'data',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expire_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'destroy_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get libraryId =>
      columnsByName['library_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get originalName =>
      columnsByName['original_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localizedName =>
      columnsByName['localized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sortName =>
      columnsByName['sort_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pages =>
      columnsByName['pages']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get wordCount =>
      columnsByName['word_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minHoursToRead =>
      columnsByName['min_hours_to_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxHoursToRead =>
      columnsByName['max_hours_to_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get avgHoursToRead =>
      columnsByName['avg_hours_to_read']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get primaryColor =>
      columnsByName['primary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryColor =>
      columnsByName['secondary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isBlacklisted =>
      columnsByName['is_blacklisted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isRecentlyAdded =>
      columnsByName['is_recently_added']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isRecentlyUpdated =>
      columnsByName['is_recently_updated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastChapterAdded =>
      columnsByName['last_chapter_added']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSynced =>
      columnsByName['last_synced']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'library_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES libraries(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'original_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'localized_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sort_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'format',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pages',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'word_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'min_hours_to_read',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'max_hours_to_read',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_16(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'avg_hours_to_read',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'primary_color',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'secondary_color',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_blacklisted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_blacklisted IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_recently_added',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (is_recently_added IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_recently_updated',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (is_recently_updated IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_chapter_added',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_synced',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seriesId =>
      columnsByName['series_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ageRating =>
      columnsByName['age_rating']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastUpdated =>
      columnsByName['last_updated']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'series_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES series(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'summary',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'age_rating',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT (-1)',
      defaultValue: const i1.CustomExpression('-1'),
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'release_year',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_30(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'last_updated',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get seriesId =>
      columnsByName['series_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get image =>
      columnsByName['image']! as i1.GeneratedColumn<i2.Uint8List>;
}

i1.GeneratedColumn<i2.Uint8List> _column_31(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'image',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get seriesMetadataId =>
      columnsByName['series_metadata_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get personId =>
      columnsByName['person_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'series_metadata_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES series_metadata(id)',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'person_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES people(id)',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get seriesMetadataId =>
      columnsByName['series_metadata_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'genre_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES genres(id)',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get seriesMetadataId =>
      columnsByName['series_metadata_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tagId =>
      columnsByName['tag_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tag_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES tags(id)',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seriesId =>
      columnsByName['series_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get minNumber =>
      columnsByName['min_number']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get maxNumber =>
      columnsByName['max_number']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get wordCount =>
      columnsByName['word_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pages =>
      columnsByName['pages']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minHoursToRead =>
      columnsByName['min_hours_to_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxHoursToRead =>
      columnsByName['max_hours_to_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get avgHoursToRead =>
      columnsByName['avg_hours_to_read']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get primaryColor =>
      columnsByName['primary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryColor =>
      columnsByName['secondary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastModified =>
      columnsByName['last_modified']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'min_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_39(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'max_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pages',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_modified',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get volumeId =>
      columnsByName['volume_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get image =>
      columnsByName['image']! as i1.GeneratedColumn<i2.Uint8List>;
}

i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'volume_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES volumes(id)ON DELETE CASCADE',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get volumeId =>
      columnsByName['volume_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seriesId =>
      columnsByName['series_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get titleName =>
      columnsByName['title_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get isbn =>
      columnsByName['isbn']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get minNumber =>
      columnsByName['min_number']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get maxNumber =>
      columnsByName['max_number']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get pages =>
      columnsByName['pages']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get wordCount =>
      columnsByName['word_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minHoursToRead =>
      columnsByName['min_hours_to_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxHoursToRead =>
      columnsByName['max_hours_to_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get avgHoursToRead =>
      columnsByName['avg_hours_to_read']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get ageRating =>
      columnsByName['age_rating']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get primaryColor =>
      columnsByName['primary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryColor =>
      columnsByName['secondary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isSpecial =>
      columnsByName['is_special']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isStoryline =>
      columnsByName['is_storyline']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get releaseDate =>
      columnsByName['release_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastModified =>
      columnsByName['last_modified']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'volume_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES volumes(id)',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'isbn',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_50(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'word_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'age_rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_special',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_special IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_storyline',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_storyline IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'release_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get chapterId =>
      columnsByName['chapter_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get image =>
      columnsByName['image']! as i1.GeneratedColumn<i2.Uint8List>;
}

i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'chapter_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES chapters(id)ON DELETE CASCADE',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get chapterId =>
      columnsByName['chapter_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get volumeId =>
      columnsByName['volume_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seriesId =>
      columnsByName['series_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get libraryId =>
      columnsByName['library_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pagesRead =>
      columnsByName['pages_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get bookScrollId =>
      columnsByName['book_scroll_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalReads =>
      columnsByName['total_reads']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastModified =>
      columnsByName['last_modified']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dirty =>
      columnsByName['dirty']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'series_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES series(id)',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'library_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES libraries(id)',
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pages_read',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'book_scroll_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_reads',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_62(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'created',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);
i1.GeneratedColumn<int> _column_63(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'last_modified',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'dirty',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (dirty IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get chapterId =>
      columnsByName['chapter_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get page =>
      columnsByName['page']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get parentPage =>
      columnsByName['parent_page']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'page',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'parent_page',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get seriesId =>
      columnsByName['series_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isWantToRead =>
      columnsByName['is_want_to_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dirty =>
      columnsByName['dirty']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_want_to_read',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (is_want_to_read IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get chapterId =>
      columnsByName['chapter_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get page =>
      columnsByName['page']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get data =>
      columnsByName['data']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSync =>
      columnsByName['last_sync']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<i2.Uint8List> _column_69(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'data',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_70(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'last_sync',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get installVersion =>
      columnsByName['install_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get onDeckProgressDays =>
      columnsByName['on_deck_progress_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get onDeckUpdateDays =>
      columnsByName['on_deck_update_days']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'install_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'on_deck_progress_days',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'on_deck_update_days',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    riverpodStorage,
    libraries,
    series,
    seriesMetadata,
    seriesCovers,
    people,
    genres,
    tags,
    seriesPeopleRoles,
    seriesGenres,
    seriesTags,
    volumes,
    volumeCovers,
    chapters,
    chapterCovers,
    readingProgress,
    bookChapters,
    wantToRead,
    downloadedPages,
    serverSettings,
    collections,
    collectionSeries,
    collectionCovers,
  ];
  late final Shape0 riverpodStorage = Shape0(
    source: i0.VersionedTable(
      entityName: 'riverpod_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 libraries = Shape1(
    source: i0.VersionedTable(
      entityName: 'libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 series = Shape2(
    source: i0.VersionedTable(
      entityName: 'series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, library_id)'],
      columns: [
        _column_4,
        _column_7,
        _column_5,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 seriesMetadata = Shape3(
    source: i0.VersionedTable(
      entityName: 'series_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 seriesCovers = Shape4(
    source: i0.VersionedTable(
      entityName: 'series_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 people = Shape5(
    source: i0.VersionedTable(
      entityName: 'people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 genres = Shape6(
    source: i0.VersionedTable(
      entityName: 'genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tags = Shape6(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 seriesPeopleRoles = Shape7(
    source: i0.VersionedTable(
      entityName: 'series_people_roles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, person_id)'],
      columns: [_column_33, _column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 seriesGenres = Shape8(
    source: i0.VersionedTable(
      entityName: 'series_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, genre_id)'],
      columns: [_column_33, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 seriesTags = Shape9(
    source: i0.VersionedTable(
      entityName: 'series_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, tag_id)'],
      columns: [_column_33, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 volumes = Shape10(
    source: i0.VersionedTable(
      entityName: 'volumes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_38,
        _column_39,
        _column_40,
        _column_13,
        _column_41,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 volumeCovers = Shape11(
    source: i0.VersionedTable(
      entityName: 'volume_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(volume_id)'],
      columns: [_column_43, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 chapters = Shape12(
    source: i0.VersionedTable(
      entityName: 'chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, volume_id, series_id)'],
      columns: [
        _column_4,
        _column_44,
        _column_25,
        _column_45,
        _column_46,
        _column_47,
        _column_26,
        _column_48,
        _column_11,
        _column_49,
        _column_38,
        _column_39,
        _column_50,
        _column_41,
        _column_51,
        _column_14,
        _column_15,
        _column_16,
        _column_52,
        _column_17,
        _column_18,
        _column_53,
        _column_54,
        _column_55,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 chapterCovers = Shape13(
    source: i0.VersionedTable(
      entityName: 'chapter_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [_column_56, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 readingProgress = Shape14(
    source: i0.VersionedTable(
      entityName: 'reading_progress',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [
        _column_56,
        _column_44,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 bookChapters = Shape15(
    source: i0.VersionedTable(
      entityName: 'book_chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page, title)'],
      columns: [_column_56, _column_65, _column_66, _column_67],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 wantToRead = Shape16(
    source: i0.VersionedTable(
      entityName: 'want_to_read',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_68, _column_64],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 downloadedPages = Shape17(
    source: i0.VersionedTable(
      entityName: 'downloaded_pages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page)'],
      columns: [_column_56, _column_66, _column_69, _column_62, _column_70],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 serverSettings = Shape18(
    source: i0.VersionedTable(
      entityName: 'server_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_71, _column_72, _column_73],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 collections = Shape19(
    source: i0.VersionedTable(
      entityName: 'collections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_65,
        _column_26,
        _column_17,
        _column_18,
        _column_74,
        _column_75,
        _column_62,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 collectionSeries = Shape20(
    source: i0.VersionedTable(
      entityName: 'collection_series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(collection_id, series_id)'],
      columns: [_column_76, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 collectionCovers = Shape21(
    source: i0.VersionedTable(
      entityName: 'collection_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(collection_id)'],
      columns: [_column_76, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get primaryColor =>
      columnsByName['primary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryColor =>
      columnsByName['secondary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get owner =>
      columnsByName['owner']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastSynced =>
      columnsByName['last_synced']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastModified =>
      columnsByName['last_modified']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_75(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_synced',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get collectionId =>
      columnsByName['collection_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seriesId =>
      columnsByName['series_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_76(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'collection_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES collections(id)ON DELETE CASCADE',
    );

class Shape21 extends i0.VersionedTable {
  Shape21({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get collectionId =>
      columnsByName['collection_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get image =>
      columnsByName['image']! as i1.GeneratedColumn<i2.Uint8List>;
}

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    riverpodStorage,
    libraries,
    series,
    seriesMetadata,
    seriesCovers,
    people,
    genres,
    tags,
    seriesPeopleRoles,
    seriesGenres,
    seriesTags,
    volumes,
    volumeCovers,
    chapters,
    chapterCovers,
    readingProgress,
    bookChapters,
    wantToRead,
    downloadedPages,
    serverSettings,
    collections,
    collectionSeries,
    collectionCovers,
  ];
  late final Shape0 riverpodStorage = Shape0(
    source: i0.VersionedTable(
      entityName: 'riverpod_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 libraries = Shape22(
    source: i0.VersionedTable(
      entityName: 'libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_5,
        _column_6,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 series = Shape2(
    source: i0.VersionedTable(
      entityName: 'series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, library_id)'],
      columns: [
        _column_4,
        _column_7,
        _column_5,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 seriesMetadata = Shape3(
    source: i0.VersionedTable(
      entityName: 'series_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 seriesCovers = Shape4(
    source: i0.VersionedTable(
      entityName: 'series_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 people = Shape5(
    source: i0.VersionedTable(
      entityName: 'people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 genres = Shape6(
    source: i0.VersionedTable(
      entityName: 'genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tags = Shape6(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 seriesPeopleRoles = Shape7(
    source: i0.VersionedTable(
      entityName: 'series_people_roles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, person_id)'],
      columns: [_column_33, _column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 seriesGenres = Shape8(
    source: i0.VersionedTable(
      entityName: 'series_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, genre_id)'],
      columns: [_column_33, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 seriesTags = Shape9(
    source: i0.VersionedTable(
      entityName: 'series_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, tag_id)'],
      columns: [_column_33, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 volumes = Shape10(
    source: i0.VersionedTable(
      entityName: 'volumes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_38,
        _column_39,
        _column_40,
        _column_13,
        _column_41,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 volumeCovers = Shape11(
    source: i0.VersionedTable(
      entityName: 'volume_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(volume_id)'],
      columns: [_column_43, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 chapters = Shape12(
    source: i0.VersionedTable(
      entityName: 'chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, volume_id, series_id)'],
      columns: [
        _column_4,
        _column_44,
        _column_25,
        _column_45,
        _column_46,
        _column_47,
        _column_26,
        _column_48,
        _column_11,
        _column_49,
        _column_38,
        _column_39,
        _column_50,
        _column_41,
        _column_51,
        _column_14,
        _column_15,
        _column_16,
        _column_52,
        _column_17,
        _column_18,
        _column_53,
        _column_54,
        _column_55,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 chapterCovers = Shape13(
    source: i0.VersionedTable(
      entityName: 'chapter_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [_column_56, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 readingProgress = Shape14(
    source: i0.VersionedTable(
      entityName: 'reading_progress',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [
        _column_56,
        _column_44,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 bookChapters = Shape15(
    source: i0.VersionedTable(
      entityName: 'book_chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page, title)'],
      columns: [_column_56, _column_65, _column_66, _column_67],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 wantToRead = Shape16(
    source: i0.VersionedTable(
      entityName: 'want_to_read',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_68, _column_64],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 downloadedPages = Shape17(
    source: i0.VersionedTable(
      entityName: 'downloaded_pages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page)'],
      columns: [_column_56, _column_66, _column_69, _column_62, _column_70],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 serverSettings = Shape18(
    source: i0.VersionedTable(
      entityName: 'server_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_71, _column_72, _column_73],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 collections = Shape19(
    source: i0.VersionedTable(
      entityName: 'collections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_65,
        _column_26,
        _column_17,
        _column_18,
        _column_74,
        _column_75,
        _column_62,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 collectionSeries = Shape20(
    source: i0.VersionedTable(
      entityName: 'collection_series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(collection_id, series_id)'],
      columns: [_column_76, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 collectionCovers = Shape21(
    source: i0.VersionedTable(
      entityName: 'collection_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(collection_id)'],
      columns: [_column_76, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape22 extends i0.VersionedTable {
  Shape22({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get includeInDashboard =>
      columnsByName['include_in_dashboard']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get includeInRecommended =>
      columnsByName['include_in_recommended']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get includeInSearch =>
      columnsByName['include_in_search']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get defaultLanguage =>
      columnsByName['default_language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastScanned =>
      columnsByName['last_scanned']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_77(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'include_in_dashboard',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (include_in_dashboard IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'include_in_recommended',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (include_in_recommended IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_79(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'include_in_search',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (include_in_search IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'default_language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_81(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_scanned',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    riverpodStorage,
    libraries,
    series,
    seriesMetadata,
    seriesCovers,
    people,
    genres,
    tags,
    seriesPeopleRoles,
    seriesGenres,
    seriesTags,
    volumes,
    volumeCovers,
    chapters,
    chapterCovers,
    readingProgress,
    bookChapters,
    wantToRead,
    downloadedPages,
    serverSettings,
    collections,
    collectionSeries,
    collectionCovers,
    readingLists,
    readingListsChapters,
    readingListCovers,
  ];
  late final Shape0 riverpodStorage = Shape0(
    source: i0.VersionedTable(
      entityName: 'riverpod_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 libraries = Shape22(
    source: i0.VersionedTable(
      entityName: 'libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_5,
        _column_6,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 series = Shape2(
    source: i0.VersionedTable(
      entityName: 'series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, library_id)'],
      columns: [
        _column_4,
        _column_7,
        _column_5,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 seriesMetadata = Shape3(
    source: i0.VersionedTable(
      entityName: 'series_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 seriesCovers = Shape4(
    source: i0.VersionedTable(
      entityName: 'series_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 people = Shape5(
    source: i0.VersionedTable(
      entityName: 'people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 genres = Shape6(
    source: i0.VersionedTable(
      entityName: 'genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tags = Shape6(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 seriesPeopleRoles = Shape7(
    source: i0.VersionedTable(
      entityName: 'series_people_roles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, person_id)'],
      columns: [_column_33, _column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 seriesGenres = Shape8(
    source: i0.VersionedTable(
      entityName: 'series_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, genre_id)'],
      columns: [_column_33, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 seriesTags = Shape9(
    source: i0.VersionedTable(
      entityName: 'series_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, tag_id)'],
      columns: [_column_33, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 volumes = Shape10(
    source: i0.VersionedTable(
      entityName: 'volumes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_38,
        _column_39,
        _column_40,
        _column_13,
        _column_41,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 volumeCovers = Shape11(
    source: i0.VersionedTable(
      entityName: 'volume_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(volume_id)'],
      columns: [_column_43, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 chapters = Shape12(
    source: i0.VersionedTable(
      entityName: 'chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, volume_id, series_id)'],
      columns: [
        _column_4,
        _column_44,
        _column_25,
        _column_45,
        _column_46,
        _column_47,
        _column_26,
        _column_48,
        _column_11,
        _column_49,
        _column_38,
        _column_39,
        _column_50,
        _column_41,
        _column_51,
        _column_14,
        _column_15,
        _column_16,
        _column_52,
        _column_17,
        _column_18,
        _column_53,
        _column_54,
        _column_55,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 chapterCovers = Shape13(
    source: i0.VersionedTable(
      entityName: 'chapter_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [_column_56, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 readingProgress = Shape14(
    source: i0.VersionedTable(
      entityName: 'reading_progress',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [
        _column_56,
        _column_44,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 bookChapters = Shape15(
    source: i0.VersionedTable(
      entityName: 'book_chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page, title)'],
      columns: [_column_56, _column_65, _column_66, _column_67],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 wantToRead = Shape16(
    source: i0.VersionedTable(
      entityName: 'want_to_read',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_68, _column_64],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 downloadedPages = Shape17(
    source: i0.VersionedTable(
      entityName: 'downloaded_pages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page)'],
      columns: [_column_56, _column_66, _column_69, _column_62, _column_70],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 serverSettings = Shape18(
    source: i0.VersionedTable(
      entityName: 'server_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_71, _column_72, _column_73],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 collections = Shape19(
    source: i0.VersionedTable(
      entityName: 'collections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_65,
        _column_26,
        _column_17,
        _column_18,
        _column_74,
        _column_75,
        _column_62,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 collectionSeries = Shape20(
    source: i0.VersionedTable(
      entityName: 'collection_series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(collection_id, series_id)'],
      columns: [_column_76, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 collectionCovers = Shape21(
    source: i0.VersionedTable(
      entityName: 'collection_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(collection_id)'],
      columns: [_column_76, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape23 readingLists = Shape23(
    source: i0.VersionedTable(
      entityName: 'reading_lists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_65,
        _column_26,
        _column_17,
        _column_18,
        _column_74,
        _column_82,
        _column_24,
        _column_62,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape24 readingListsChapters = Shape24(
    source: i0.VersionedTable(
      entityName: 'reading_lists_chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(reading_list_id, chapter_id)'],
      columns: [_column_83, _column_56, _column_84],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape25 readingListCovers = Shape25(
    source: i0.VersionedTable(
      entityName: 'reading_list_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(reading_list_id)'],
      columns: [_column_83, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape23 extends i0.VersionedTable {
  Shape23({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get primaryColor =>
      columnsByName['primary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryColor =>
      columnsByName['secondary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get owner =>
      columnsByName['owner']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastSyncCheck =>
      columnsByName['last_sync_check']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSynced =>
      columnsByName['last_synced']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastModified =>
      columnsByName['last_modified']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_82(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_sync_check',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape24 extends i0.VersionedTable {
  Shape24({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get readingListId =>
      columnsByName['reading_list_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get chapterId =>
      columnsByName['chapter_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get order =>
      columnsByName['order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_83(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reading_list_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES reading_lists(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_84(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape25 extends i0.VersionedTable {
  Shape25({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get readingListId =>
      columnsByName['reading_list_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get image =>
      columnsByName['image']! as i1.GeneratedColumn<i2.Uint8List>;
}

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    riverpodStorage,
    libraries,
    series,
    seriesMetadata,
    seriesCovers,
    people,
    genres,
    tags,
    seriesPeopleRoles,
    seriesGenres,
    seriesTags,
    volumes,
    volumeCovers,
    chapters,
    chapterCovers,
    readingProgress,
    bookChapters,
    wantToRead,
    downloadedPages,
    serverSettings,
    collections,
    collectionSeries,
    collectionCovers,
    readingLists,
    readingListsChapters,
    readingListCovers,
    sidenav,
  ];
  late final Shape0 riverpodStorage = Shape0(
    source: i0.VersionedTable(
      entityName: 'riverpod_storage',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 libraries = Shape22(
    source: i0.VersionedTable(
      entityName: 'libraries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_5,
        _column_6,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 series = Shape2(
    source: i0.VersionedTable(
      entityName: 'series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, library_id)'],
      columns: [
        _column_4,
        _column_7,
        _column_5,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 seriesMetadata = Shape3(
    source: i0.VersionedTable(
      entityName: 'series_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 seriesCovers = Shape4(
    source: i0.VersionedTable(
      entityName: 'series_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 people = Shape5(
    source: i0.VersionedTable(
      entityName: 'people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 genres = Shape6(
    source: i0.VersionedTable(
      entityName: 'genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tags = Shape6(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 seriesPeopleRoles = Shape7(
    source: i0.VersionedTable(
      entityName: 'series_people_roles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, person_id)'],
      columns: [_column_33, _column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 seriesGenres = Shape8(
    source: i0.VersionedTable(
      entityName: 'series_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, genre_id)'],
      columns: [_column_33, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 seriesTags = Shape9(
    source: i0.VersionedTable(
      entityName: 'series_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_metadata_id, tag_id)'],
      columns: [_column_33, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 volumes = Shape10(
    source: i0.VersionedTable(
      entityName: 'volumes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, series_id)'],
      columns: [
        _column_4,
        _column_25,
        _column_38,
        _column_39,
        _column_40,
        _column_13,
        _column_41,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 volumeCovers = Shape11(
    source: i0.VersionedTable(
      entityName: 'volume_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(volume_id)'],
      columns: [_column_43, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 chapters = Shape12(
    source: i0.VersionedTable(
      entityName: 'chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(id, volume_id, series_id)'],
      columns: [
        _column_4,
        _column_44,
        _column_25,
        _column_45,
        _column_46,
        _column_47,
        _column_26,
        _column_48,
        _column_11,
        _column_49,
        _column_38,
        _column_39,
        _column_50,
        _column_41,
        _column_51,
        _column_14,
        _column_15,
        _column_16,
        _column_52,
        _column_17,
        _column_18,
        _column_53,
        _column_54,
        _column_55,
        _column_22,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 chapterCovers = Shape13(
    source: i0.VersionedTable(
      entityName: 'chapter_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [_column_56, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 readingProgress = Shape14(
    source: i0.VersionedTable(
      entityName: 'reading_progress',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id)'],
      columns: [
        _column_56,
        _column_44,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 bookChapters = Shape15(
    source: i0.VersionedTable(
      entityName: 'book_chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page, title)'],
      columns: [_column_56, _column_65, _column_66, _column_67],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 wantToRead = Shape16(
    source: i0.VersionedTable(
      entityName: 'want_to_read',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(series_id)'],
      columns: [_column_25, _column_68, _column_64],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 downloadedPages = Shape17(
    source: i0.VersionedTable(
      entityName: 'downloaded_pages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_id, page)'],
      columns: [_column_56, _column_66, _column_69, _column_62, _column_70],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 serverSettings = Shape18(
    source: i0.VersionedTable(
      entityName: 'server_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_71, _column_72, _column_73],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 collections = Shape19(
    source: i0.VersionedTable(
      entityName: 'collections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_65,
        _column_26,
        _column_17,
        _column_18,
        _column_74,
        _column_75,
        _column_62,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 collectionSeries = Shape20(
    source: i0.VersionedTable(
      entityName: 'collection_series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(collection_id, series_id)'],
      columns: [_column_76, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 collectionCovers = Shape21(
    source: i0.VersionedTable(
      entityName: 'collection_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(collection_id)'],
      columns: [_column_76, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape23 readingLists = Shape23(
    source: i0.VersionedTable(
      entityName: 'reading_lists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_65,
        _column_26,
        _column_17,
        _column_18,
        _column_74,
        _column_82,
        _column_24,
        _column_62,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape24 readingListsChapters = Shape24(
    source: i0.VersionedTable(
      entityName: 'reading_lists_chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(reading_list_id, chapter_id)'],
      columns: [_column_83, _column_56, _column_84],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape25 readingListCovers = Shape25(
    source: i0.VersionedTable(
      entityName: 'reading_list_covers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(reading_list_id)'],
      columns: [_column_83, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape26 sidenav = Shape26(
    source: i0.VersionedTable(
      entityName: 'sidenav',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_40,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape26 extends i0.VersionedTable {
  Shape26({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get order =>
      columnsByName['order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get visible =>
      columnsByName['visible']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get streamType =>
      columnsByName['stream_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get libraryId =>
      columnsByName['library_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_85(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'visible',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (visible IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stream_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_87(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'library_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
  ),
);
